name: Update Instagram Feed Gist

on:
  schedule:
    - cron: "0 0 * * *" # Run once a day at midnight
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Instagram Feed Data
        env:
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
        run: |
          echo "[]" > feed.json  # Placeholder file in case data fetching fails
          curl -s "https://graph.instagram.com/me/media?fields=media_url,thumbnail_url,media_type,permalink&limit=5&access_token=$INSTAGRAM_ACCESS_TOKEN" -o response.json
          jq '.data | map({href: .permalink, src: (if .media_type == "VIDEO" then .thumbnail_url else .media_url end)})' response.json > feed.json

      - name: Update Gist with JSON
        env:
          GIST_ID: ${{ vars.GIST_ID }}
        run: |
          CONTENT=$(cat feed.json | jq -c .)
          curl -X PATCH \
            -d "{\"files\": {\"instafeed.json\": {\"content\": $(echo "$CONTENT" | jq -R .)}}}" \
            https://api.github.com/gists/$GIST_ID
