name: Update Instagram Feed Gist

on:
  schedule:
    - cron: "0 */3 * * *" # Every 3 hours at minute 0
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Instagram Feed Data
        env:
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
        run: |
          echo "[]" > feed.json  # Placeholder file in case data fetching fails
          curl -s "https://graph.facebook.com/v20.0/$IG_USER_ID/media?access_token=$IG_ACCESS_TOKEN&fields=media_url,media_type,permalink,thumbnail_url&limit=5" -o response.json
          jq '.data | map({href: .permalink, src: (if .media_type == "VIDEO" then .thumbnail_url else .media_url end)})' response.json > feed.json

      - name: Update Gist with JSON
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ vars.GIST_ID }}
        run: |
          CONTENT=$(cat feed.json | jq -c .)
          echo "Updating Gist with content: $CONTENT"  # Debugging line
          curl -X PATCH \
            -H "Authorization: token $GIST_TOKEN" \
            -d "{\"files\": {\"instafeed.json\": {\"content\": $(echo "$CONTENT" | jq -R .)}}}" \
            https://api.github.com/gists/$GIST_ID
